FROM ubuntu:20.04 AS builder

RUN apt update && apt install git -y

WORKDIR /
RUN git clone https://github.com/gabrielecirulli/2048.git

WORKDIR /2048/
RUN rm -rf CONTRIBUTING.md LICENSE.txt README.md Rakefile
RUN env


FROM nginx:alpine
WORKDIR /
RUN rm -rf /usr/share/nginx/html
COPY --from=builder 2048/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]